###服务启动端口号
server:
  port: 9201
###服务名称(服务注册到eureka名称)
spring:
  application:
    name: ljq-provider
###服务注册到eureka地址
eureka:
  client:
    service-url:
      defaultZone: http://localhost:9100/eureka

    register-with-eureka: true
    ###是否需要从eureka上获取注册信息
    fetch-registry: true